USE [master]
GO

/****** Object:  Database [Shifts]    Script Date: 2/09/2021 5:08:34 p. m. ******/
CREATE DATABASE [Shifts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shifts', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Shifts.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shifts_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Shifts_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shifts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shifts] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shifts] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shifts] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shifts] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shifts] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shifts] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Shifts] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shifts] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shifts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shifts] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shifts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shifts] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shifts] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shifts] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shifts] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Shifts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shifts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shifts] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shifts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shifts] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shifts] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shifts] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shifts] SET RECOVERY FULL 
GO

ALTER DATABASE [Shifts] SET  MULTI_USER 
GO

ALTER DATABASE [Shifts] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shifts] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shifts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shifts] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Shifts] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shifts] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Shifts] SET  READ_WRITE 
GO


